name       : haskell-src-exts
version    : 1.17.1
release    : 2
source     :
    - http://hackage.haskell.org/package/haskell-src-exts-1.17.1.tar.gz : ba5c547720514515ad0b94eb8a3d7e22a0e2ad2d85b5e1d178e62c61615528bd
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell-Source with Extensions (HSE, haskell-src-exts) is a standalone parser for Haskell.
description: |
    Haskell-Source with Extensions (HSE, haskell-src-exts) is a standalone parser for Haskell. In addition to standard Haskell, all extensions implemented in GHC are supported.
builddeps  :
    - cpphs
    - haskell-cabal-install
    - haskell-happy
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
