name       : haskell-src-exts
version    : 1.19.1
release    : 1
source     :
    - http://hackage.haskell.org/package/haskell-src-exts-1.19.1/haskell-src-exts-1.19.1.tar.gz : f0f5b2867673d654c7cce8a5fcc69222ea09af460c29a819c23cccf6311ba971
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell-Source with Extensions (HSE, haskell-src-exts) is a standalone parser for Haskell.
description: |
    Haskell-Source with Extensions (HSE, haskell-src-exts) is a standalone parser for Haskell. In addition to standard Haskell, all extensions implemented in GHC are supported.
builddeps  :
    - cpphs
    - haskell-cabal-install
    - haskell-happy
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
