name       : haskell-src-exts
version    : 1.23.1
release    : 4
source     :
    - https://hackage.haskell.org/package/haskell-src-exts-1.23.1/haskell-src-exts-1.23.1.tar.gz : 67853047169fff7d3e5d87acef214ee185a6ab8c6a104ed9c59e389574cf6c05
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell-Source with Extensions (HSE, haskell-src-exts) is a standalone parser for Haskell.
description: |
    Haskell-Source with Extensions (HSE, haskell-src-exts) is a standalone parser for Haskell. In addition to standard Haskell, all extensions implemented in GHC are supported.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
    - haskell-happy
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
